#!/system/xbin/sh


# if booted a custom kernel, reset flag for next reboot
# FLASHTOOL KERNEL ADDON. DO NOT DELETE
if [ -e /system/kernel/kexecbooted ]
then
    mount -o remount,rw yaffs2 /system
    mv /system/kernel/kexecbooted /system/kernel/kexecboot
fi
