#!/system/xbin/sh

mount -o remount,rw yaffs2 /system

export KVER=`uname -r`

for i in `ls /system/lib/modules/*ko`
do
	export FILE=`echo $i|cut -d "/" -f 5`
	if [ ! -e /system/kernel/$KVER/modules/$FILE ]
	then
		rm /system/lib/modules/$FILE
	fi
done

for i in `ls /system/kernel/$KVER/modules/*ko`
do
	export FILE=`echo $i|cut -d "/" -f 6`
	export CKSUMNEW=`cksum /system/kernel/$KVER/modules/$FILE|awk '{print $1 $2}'`
	export CKSUMOLD=`cksum /system/lib/modules/$FILE|awk '{print $1 $2}'`
	if [ "$CKSUMNEW" != "$CKSUMOLD" ]
	then
		rm /system/lib/modules/$FILE
		cp /system/kernel/$KVER/modules/$FILE /system/lib/modules
		chmod 644 /system/lib/modules/$FILE
	fi
done