#!/system/xbin/sh

/system/bin/charger

# if the file exists then no need to catch button events
if [ ! -e /data/local/tmp/recoveryboot -a ! -e /cache/recovery/boot ]
then
	export DEVICE=`cat /system/recovery/model`

	case $DEVICE in
		X10*)
			cat /dev/input/event2 > /dev/keycheck& ;;
		E10*)
			cat /dev/input/event1 > /dev/keycheck& ;;
       U20*)
           cat /dev/input/event0 > /dev/keycheck& ;;
       E15*)
           cat /dev/input/event1 > /dev/keycheck& ;;
   esac

   sleep 3
   kill -9 $!
	if [ -s /dev/keycheck ]
	then
		sync
		hexdum /dev/keycheck > /data/local/tmp/hexdump.log
		touch /cache/recovery/boot
		sync
	fi
fi

if [ -e /data/local/tmp/kexecboot ]
then
	export KEXECFILE=/data/local/tmp/kexecboot
else
	export KEXECFILE=/system/kernel/default
fi

if [ -e /data/local/tmp/recovery ]
then
	export RECOVERYFILE=/data/local/tmp/recovery
else
	export RECOVERYFILE=/system/recovery/default
fi

export KERNELMETHOD=`cat $KEXECFILE|grep kernelmethod|cut -d "=" -f 2`

if [ $KERNELMETHOD = "custom" ]
then
	echo "Booting custom kernel" >> /data/local/tmp/chargemon.log
	export KERNELIMAGE=`cat $KEXECFILE|grep kernelimage|cut -d "=" -f 2`
	echo $KERNELIMAGE >> /data/local/tmp/chargemon.log
	if [ -s /dev/keycheck -o -e /data/local/tmp/recoveryboot -o -e /cache/recovery/boot ]
	then
		export KERNELRECOVERY=`cat $KEXECFILE|grep kernelrecovery|cut -d "=" -f 2`
		if [ "$KERNELRECOVERY" = "true" ]
		then
			/system/bin/splboot --mode=recovery --image=$KERNELIMAGE
		else
			export RECOVERYMETHOD=`cat $RECOVERYFILE|grep recoverymethod|cut -d "=" -f 2`
			export RECOVERYIMAGE=`cat $RECOVERYFILE|grep recoveryimage|cut -d "=" -f 2`
			if [ "$RECOVERYMETHOD" = "kernel" ]
			then
				/system/bin/splboot --mode=recovery --image=$RECOVERYIMAGE
			else
				export RECOVERYCOMPRESSION=`cat $RECOVERYFILE|grep recoverycompression|cut -d "=" -f 2`
				/system/bin/ramdiskswitch --compression=$RECOVERYCOMPRESSION --image=$RECOVERYIMAGE
			fi
		fi
	else
		/system/bin/splboot --mode=kernel --image=$KERNELIMAGE
	fi
else
	if [ -e /data/local/tmp/recoveryboot -o -e /cache/recovery/boot ]
	then
		export RECOVERYMETHOD=`cat $RECOVERYFILE|grep recoverymethod|cut -d "=" -f 2`
		export RECOVERYIMAGE=`cat $RECOVERYFILE|grep recoveryimage|cut -d "=" -f 2`
		if [ "$RECOVERYMETHOD" = "kernel" ]
		then
			/system/bin/splboot --mode=recovery --image=$RECOVERYIMAGE
		else
			export RECOVERYCOMPRESSION=`cat $RECOVERYFILE|grep recoverycompression|cut -d "=" -f 2`
			/system/bin/ramdiskswitch --compression=$RECOVERYCOMPRESSION --image=$RECOVERYIMAGE
		fi
	fi
fi

# Continue booting
exit