#!/system/bin/sh

export PATH=/sbin:/system/sbin:/system/bin:/system/xbin

while test $# != 0
do
  case $1 in
  --*=*)
    ac_option=`expr "X$1" : 'X\([^=]*\)='`
    ac_optarg=`expr "X$1" : 'X[^=]*=\(.*\)'`
    ac_shift=:
    ;;
  *)
    ac_option=$1
    ac_optarg=$2
    ac_shift=shift
    ;;
  esac

  case $ac_option in
  -mode | --mode)
     export p_mode=$ac_optarg;;
  -image | --image)
     export p_image=$ac_optarg;;
  esac
  shift
done

if [ "$p_mode" = "recovery" ]
then
	rm -r /data/local/tmp/recoveryboot
	touch /cache/recovery/boot
fi

if [ -e $p_image ]
then
	umount /cache
	umount /sdcard
	umount /cdrom
	umount /data/DxDrm/fuse
	killall -9 DxDrmServerIpc
	for i in `ls /system/kernel/spl*`
	do
		insmod $i
	done
	sync
	cat /system/kernel/miniloader > /proc/splboot/image
	cat $p_image > /proc/splboot/boot_img
	echo > /proc/splboot/boot
fi